@startuml
actor Client
participant StudEngAPI
database DB.words
hide footbox

== 英単語登録 ==

Client -> StudEngAPI : 英単語リクエスト条件付き
activate StudEngAPI
  group 過去に登録した英単語取得
    StudEngAPI -> DB.words : 条件ごとに単語取得
    activate DB.words

    StudEngAPI <-- DB.words :
    deactivate DB.words
  end

  Client <-- StudEngAPI :

deactivate StudEngAPI
@enduml