@startuml
actor Client
participant StudEngAPI
database DB
hide footbox

== ログイン ==

Client -> StudEngAPI : メール・パスワード
activate StudEngAPI
  group ユーザー認証・トークン発行
    StudEngAPI -> DB : ユーザ認証
    activate DB

    StudEngAPI <-- DB : 認証できたか確認
    deactivate DB
  end

  Client <-- StudEngAPI : トークン発行
    note right: JWT発行
deactivate StudEngAPI
@enduml